import {
  MutableRefObject,
  useCallback,
  useEffect,
  useRef,
  useState,
} from "react";
import { enqueueSnackbar } from "components/MessageBox";
import {
  createManualMepaExtractedItem,
  getMepaExtractedItems,
  matchMepaProducts,
  runMepaProductAgentsPipeline,
  runMepaProductMatchingBatch,
  updateMepaExtractedItem,
  updateMepaProductMatchValidation,
} from "../fetchData/mepaAi";
import type { ExtractedItemView } from "../features/products/products.types";
import type {
  MepaAiProductCandidate,
  MepaProductAgentsPipelineResult,
  MepaProductMatchingBatchResult,
  MepaProductSearchResponseData,
} from "../types";

type UseMepaProductsControllerParams = {
  abortController: MutableRefObject<AbortController | null>;
  tenderId?: string | null;
  setLoading: (loading: string | null) => void;
  refreshWorkspaceData: (
    tenderId?: string,
    options?: { force?: boolean },
  ) => Promise<void> | void;
};

type ValidateProductMatchParams = {
  itemId: string;
  action:
    | "VALIDATE_BEST_MATCH"
    | "VALIDATE_SUBSTITUTE"
    | "REJECT"
    | "NEEDS_REVIEW"
    | "MANUAL_OVERRIDE";
  selectedCandidateRef?: string | null;
  manualProduct?: Record<string, unknown> | null;
  reason?: string | null;
};

/**
 * Owns the MEPA product extraction and catalog matching workflow.
 *
 * Product review is one of the heaviest areas of the tender workspace: it can
 * trigger extraction, Vespa matching, manual item edits and human-in-the-loop
 * match governance. Keeping this workflow outside the page container prevents
 * state churn in the shell and gives every async operation a stale-response
 * guard when the user switches tender while requests are still in flight.
 */
export function useMepaProductsController({
  abortController,
  tenderId,
  setLoading,
  refreshWorkspaceData,
}: UseMepaProductsControllerParams) {
  // Sequence guard for product list requests. Incrementing it invalidates older
  // responses without needing to abort every low-level HTTP request.
  const loadItemsSeqRef = useRef(0);

  // Sequence guard for manual catalog search requests.
  const searchSeqRef = useRef(0);

  // Canonical rows extracted from tender documents or manually created by user.
  const [extractedItems, setExtractedItems] = useState<ExtractedItemView[]>([]);

  // Draft query used by the manual product search drawer.
  const [productQuery, setProductQuery] = useState(
    "Notebook 15.6 i7 16GB RAM SSD 512GB",
  );
  // Catalog candidates returned for the manual search query.
  const [candidates, setCandidates] = useState<MepaAiProductCandidate[]>([]);

  // Raw-ish search metadata used for diagnostics and score explanation.
  const [productSearchMeta, setProductSearchMeta] = useState<
    Partial<MepaProductSearchResponseData>
  >({});
  // Last batch matching result generated by Vespa/catalog matching.
  const [productBatchResult, setProductBatchResult] =
    useState<MepaProductMatchingBatchResult | null>(null);

  // Last multi-agent product pipeline output. Kept separate from batch result
  // because extraction and matching can be executed independently.
  const [productAgentsPipelineResult, setProductAgentsPipelineResult] =
    useState<MepaProductAgentsPipelineResult | null>(null);

  /**
   * Clears product-domain read models on tender change.
   *
   * Incrementing both sequence refs makes any in-flight list/search response
   * harmless if it resolves after the selected tender has changed.
   */
  const resetProductsState = useCallback(() => {
    loadItemsSeqRef.current += 1;
    searchSeqRef.current += 1;
    setExtractedItems([]);
    setCandidates([]);
    setProductSearchMeta({});
    setProductBatchResult(null);
    setProductAgentsPipelineResult(null);
  }, []);

  // Product state is strictly tender-scoped.
  useEffect(() => {
    resetProductsState();
  }, [tenderId, resetProductsState]);

  /** Loads extracted/manual product rows for the selected tender. */
  const loadProducts = useCallback(async () => {
    if (!tenderId) return;
    const requestSeq = ++loadItemsSeqRef.current;
    try {
      setLoading("items");
      const res = await getMepaExtractedItems({ abortController, tenderId });
      if (requestSeq !== loadItemsSeqRef.current) return;
      setExtractedItems(res?.data?.items ?? []);
    } catch (error) {
      console.error(error);
      enqueueSnackbar?.("Non riesco a caricare i prodotti estratti.", {
        variant: "warning",
      } as any);
    } finally {
      if (requestSeq === loadItemsSeqRef.current) setLoading(null);
    }
  }, [abortController, tenderId, setLoading]);

  /** Runs manual catalog search for the current productQuery. */
  const matchProducts = useCallback(async () => {
    if (!tenderId) return;
    const requestSeq = ++searchSeqRef.current;
    try {
      setLoading("products");
      const res = await matchMepaProducts({
        abortController,
        tenderId,
        description: productQuery,
        includeIcecat: true,
        limit: 8,
      });
      if (requestSeq !== searchSeqRef.current) return;
      setCandidates(res?.data?.candidates ?? []);
      setProductSearchMeta(res?.data ?? {});
    } catch (error) {
      console.error(error);
      enqueueSnackbar?.(
        "Product Search non disponibile o capability mancante.",
        { variant: "warning" } as any,
      );
    } finally {
      if (requestSeq === searchSeqRef.current) setLoading(null);
    }
  }, [abortController, productQuery, tenderId, setLoading]);

  /**
   * Runs the full Product Requirements + Catalog Matching agentic pipeline.
   *
   * This operation can update multiple read models, so after completion it
   * reloads product rows and stores both pipeline and batch summaries.
   */
  const runProductAgentsPipeline = useCallback(async () => {
    if (!tenderId) return;
    try {
      setLoading("product-agents-pipeline");
      const res = await runMepaProductAgentsPipeline({
        abortController,
        tenderId,
        forceRebuild: true,
        includeIcecat: true,
        limitPerItem: 12,
        maxItems: 160,
      });
      setProductAgentsPipelineResult(res?.data ?? null);
      setProductBatchResult(res?.data?.productMatchingBatch ?? null);
      await loadProducts();
      const extracted = res?.data?.extractedItems ?? 0;
      const matched =
        res?.data?.productCatalogMatchingSummary?.recommendedProducts ?? 0;
      enqueueSnackbar?.(
        `Pipeline prodotti completata: ${extracted} righe estratte, ${matched} con proposta catalogo.`,
        { variant: "success" } as any,
      );
    } catch (error) {
      console.error(error);
      enqueueSnackbar?.(
        "Pipeline Product requirements / catalog matching non riuscita.",
        { variant: "warning" } as any,
      );
    } finally {
      setLoading(null);
    }
  }, [abortController, loadProducts, tenderId, setLoading]);

  /** Runs catalog matching only for already extracted/validated rows. */
  const runProductMatchingBatch = useCallback(async () => {
    if (!tenderId) return;
    try {
      setLoading("product-batch");
      const res = await runMepaProductMatchingBatch({
        abortController,
        tenderId,
        validationStatuses: ["VALIDATED", "CORRECTED", "PENDING_REVIEW"],
        includeIcecat: true,
        limitPerItem: 8,
        maxItems: 100,
        onlyWithEvidence: true,
        minFinalScore: 0.5,
      });
      setProductBatchResult(res?.data ?? null);
      await loadProducts();
      enqueueSnackbar?.("Matching Vespa sulle righe validate completato.", {
        variant: "success",
      } as any);
    } catch (error) {
      console.error(error);
      enqueueSnackbar?.(
        "Matching massivo prodotti non disponibile o capability mancante.",
        { variant: "warning" } as any,
      );
    } finally {
      setLoading(null);
    }
  }, [abortController, loadProducts, tenderId, setLoading]);

  /**
   * Applies a user correction to an extracted item.
   *
   * The workspace is force-refreshed afterwards because readiness and overview
   * counters depend on row validation status.
   */
  const updateExtractedItem = useCallback(
    async (itemId: string, patch: Record<string, unknown>) => {
      if (!tenderId) return;
      try {
        setLoading("item-update");
        await updateMepaExtractedItem({
          abortController,
          tenderId,
          itemId,
          patch,
        });
        enqueueSnackbar?.("Riga prodotto aggiornata.", {
          variant: "success",
        } as any);
        await loadProducts();
        await refreshWorkspaceData(tenderId, { force: true });
      } catch (error) {
        console.error(error);
        enqueueSnackbar?.("Non riesco ad aggiornare la riga prodotto.", {
          variant: "error",
        } as any);
      } finally {
        setLoading(null);
      }
    },
    [abortController, loadProducts, refreshWorkspaceData, tenderId, setLoading],
  );

  /** Saves human governance for a suggested catalog match. */
  const validateProductMatch = useCallback(
    async (params: ValidateProductMatchParams) => {
      if (!tenderId) return;
      try {
        setLoading("product-match-validation");
        await updateMepaProductMatchValidation({
          abortController,
          tenderId,
          ...params,
        });
        enqueueSnackbar?.("Governance match prodotto salvata.", {
          variant: "success",
        } as any);
        await loadProducts();
      } catch (error) {
        console.error(error);
        enqueueSnackbar?.(
          "Non riesco a salvare la validazione del match prodotto.",
          { variant: "error" } as any,
        );
      } finally {
        setLoading(null);
      }
    },
    [abortController, loadProducts, tenderId, setLoading],
  );

  /** Creates a manual product/service row when extraction misses a requirement. */
  const createManualExtractedItem = useCallback(
    async (item: Record<string, unknown>) => {
      if (!tenderId) return;
      try {
        setLoading("item-create");
        await createManualMepaExtractedItem({
          abortController,
          tenderId,
          item,
        });
        enqueueSnackbar?.("Riga manuale aggiunta.", {
          variant: "success",
        } as any);
        await loadProducts();
        await refreshWorkspaceData(tenderId, { force: true });
      } catch (error) {
        console.error(error);
        enqueueSnackbar?.("Non riesco ad aggiungere la riga manuale.", {
          variant: "error",
        } as any);
      } finally {
        setLoading(null);
      }
    },
    [abortController, loadProducts, refreshWorkspaceData, tenderId, setLoading],
  );

  return {
    extractedItems,
    productQuery,
    setProductQuery,
    candidates,
    productSearchMeta,
    productBatchResult,
    productAgentsPipelineResult,
    resetProductsState,
    loadProducts,
    matchProducts,
    runProductMatchingBatch,
    runProductAgentsPipeline,
    updateExtractedItem,
    validateProductMatch,
    createManualExtractedItem,
  };
}
