/**
 * Product-review domain types used by the MEPA front-end.
 *
 * These types are intentionally UI-facing and tolerant. The AI service can add
 * evidence, ranking metadata or catalog-specific fields without forcing an
 * immediate UI refactor. Components must therefore treat nested `match` payloads
 * as read models and use products.utils/products.selectors for business-facing
 * decisions such as bucket, top candidate and proposal kind.
 */

/**
 * UI-facing representation of an extracted tender item.
 *
 * The object intentionally preserves loose match/evidence payloads because the
 * AI service evolves faster than the visual review workflow. All business
 * decisions must go through selectors in products.utils.ts instead of reading
 * nested fields directly from JSX components.
 */
export type ExtractedItemView = {
    /** Mongo/document identifier of the extracted item, when already persisted. */
    _id?: string;
    /** Raw row description as found in the tender documents. */
    originalDescription?: string;
    /** AI-normalized description used for search, matching and buyer review. */
    normalizedDescription?: string;
    /** Requested quantity. Nullable because some tenders expose quantities only in attachments or notes. */
    quantity?: number | null;
    /** Unit of measure displayed to the buyer, for example PZ, NR, cad. */
    unit?: string | null;
    /** Validation state assigned by AI or by the human review workflow. */
    validationStatus?: string;
    /** References generated by newer pipelines. Kept loose to support evidence schema evolution. */
    sourceEvidenceRefs?: Array<Record<string, any>>;
    /** Backward-compatible evidence references used by earlier analysis jobs. */
    evidenceRefs?: Array<Record<string, any>>;
    /** Product matching read model: candidates, recommendation, lot, technical attributes and diagnostics. */
    match?: Record<string, any>;
    /** True when the row was generated by AI extraction instead of manually inserted by the user. */
    createdFromAi?: boolean;
};

/**
 * Buyer-facing match buckets used by filters and KPIs.
 *
 * READY means the system found a usable recommendation. BUYER_REVIEW means the
 * recommendation exists but still needs human judgement. NO_MATCH means the row
 * is not currently actionable through catalog matching. MANUAL identifies rows
 * intentionally resolved through manual user intervention.
 */
export type ProductMatchBucket = "READY" | "BUYER_REVIEW" | "NO_MATCH" | "MANUAL";

/**
 * Semantic type of the proposal selected for a row.
 *
 * Keeping this union separate from raw API labels protects the UI from backend
 * ranking-policy changes and makes badge rendering deterministic.
 */
export type ProductProposalKind = "BEST" | "SUBSTITUTE" | "NONE" | "MANUAL";
